DROP DATABASE activiti;

CREATE DATABASE activiti;

CREATE TABLE IF NOT EXISTS USERS
(
    ID INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS EMAILS
(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    EMAIL VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLES
(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    ROLE VARCHAR(32) NOT NULL
);

